### ISSUE TITLE
A advice about ```code annotation```

### ISSUE THREAD

**Issue by hongrunhui** [crisward/riot-tag#11]
Hi,I am glad to use ```riot-tag``` in ```vscode```,but it still had a question which about ```code annotation```,like this ```.tag``` file:
```
<mytag>
  <div>content</div>
  <script>
     let self = this;
     code....//when I want to annotate the codes ,it used ```<!--codes-->``` rather than ```//codes```,
//and the codes still have ```colors(highlight)```,so I suggest that u can fixed this problem by using ```//codes``` in the ```<script></script>```
  </script>
</mytag>
```
thanks!

**Comment by crisward** [comment]
VSCode only allows me to specify one comment type  here - https://github.com/crisward/riot-tag/blob/master/riot.configuration.json#L2 

As for how it interprets this is up to vscode. I tell it everything in <script> tags should be treated as js, so it should use js comments.

The example you gave looks like this in my vscode. Which is what id would expect.

<img width="1112" alt="screen shot 2018-05-16 at 08 42 04" src="https://user-images.githubusercontent.com/3109157/40103370-17d62c9a-58e5-11e8-9480-f7cb811b168a.png">
