### ISSUE TITLE
0.1.8 version release

### ISSUE THREAD

**Issue by dmnrmr** [crisward/riot-tag#12]
It looks like version 0.1.8 is not released to vscode extension marketplace.

**Comment by crisward** [comment]
I know... I'll have to brush off my notes on how to do it. I saw the earlier comment. I suppose I should really push it from here - https://github.com/riot/syntax-highlight

**Comment by crisward** [comment]
Just remembered why I didn't push this. I merged the jade and html syntax highlighters together and they didn't get on. The first word  a new line gets highlighted red if I remember correctly. I pencil this in to fix, then push.
