### ISSUE TITLE
How to turn on Emmet support and other things related to HTML / CSS?

### ISSUE THREAD

**Issue by thecosss** [crisward/riot-tag#13]
I want to write 'my-tag', hit Tab and it should expand to <my-tag></my-tag>
When cursor is inside of a tag and i hit Enter proper indentation should take effect like it does in plain html.
Thanks in advance!

**Comment by crisward** [comment]
Closing this issue as it's old, and I really have no idea how to support emmet in a syntax highlighter. Sorry.
