### ISSUE TITLE
Highlighting syntax errors

### ISSUE THREAD

**Issue by amitguptagwl** [crisward/riot-tag#14]
Thanks to write this useful plugin.

Before I use this plugin I was using setting the language mode to HTML. But vscode was reporting extra syntax errors as the function start without `function` keyword.

After installing this plugin vscode now don't report any syntax error. Can it be fixed?

**Comment by amitguptagwl** [comment]
I believe vscode treats the document as HTML in this case. Hence when I use keys to comment the code it uses HTML comment `<!-- -->`.

**Comment by crisward** [comment]
This plugin just does syntax highlighting. VSCode's error checking isn't something I know a great deal about, though I'm fairly sure it'll require you to use one of their default language plugins.
