### ISSUE TITLE
GT in riot expression break highlighting 

### ISSUE THREAD

**Issue by zorgoz** [crisward/riot-tag#15]
Syntax like `<div if={ stage >=0 } class="uk-margin-small-bottom uk-form-horizontal">` breaks highlighting as `>` is considered tag closing instead of operator.

![image](https://user-images.githubusercontent.com/1569170/48861255-6db84a80-edc3-11e8-827d-00816ad17c7f.png)
Using LE instead will not break it:
![image](https://user-images.githubusercontent.com/1569170/48861300-89bbec00-edc3-11e8-93e7-57a741c207e3.png)

**Comment by crisward** [comment]
You can use "quotes" around your expressions to prevent this. It also prevents some other parsing issues so isn't a bad idea.
