### ISSUE TITLE
intelligent comment syntax

### ISSUE THREAD

**Issue by SassNinja** [crisward/riot-tag#17]
@crisward  first of all thanks for the extension!
But there's one thing I'm really really missing: intelligent, section aware comment syntax!

When I use a shortcut to toggle comment, it always uses the html comment syntax even within the `script` tag.
So you end up with something like this
```html
<some-example>
	<h1>bad</h1>
	<script>
        <!-- console.log(':/'); -->
    </script>
</some-example>
```

I've seen there was a similar feature request in the past (https://github.com/crisward/riot-tag/issues/4) which you've closed, explaining it's caused by vscode.

In the meantime two years have been past – is this still correct?
I'm asking because other extensions don't have that problem, for example `Vetur` for vue templates.

```vue
<template>
    <h1>{{ title }}</h1>
</template>

<script>
  module.exports = {
    data: function () {
      return {
        title: 'Test'
      };
    }
  };
</script>

<style scoped>
  h1 {
    text-transform: uppercase;
  }
</style>
```

Here it's working as expected: the comment syntax depends on the section.
Any idea how this works and how to adopt it?

**Comment by paulkamer** [comment]
This extension always comments-out lines with `// `: https://github.com/nesterow/riot-vsc

It even does it for HTML/template tags, which IMO is less annoying, since I tend to comment out those lines much less frequently.

So perhaps this is a 'solution'; simply always use `//` for comments?

**Comment by crisward** [comment]
Fair point. Out of interest which editor do you use, is it vs code?

**Comment by SassNinja** [comment]
> So perhaps this is a 'solution'; simply always use // for comments?

@paulkamer I'm afraid that's not a satisfying solution for me because I'm often toggling comments in HTML as well :/

> Out of interest which editor do you use, is it vs code?

@crisward what do you mean??? your extension is made for vscode so of course it's vscode!

**Comment by crisward** [comment]
This extension was previously used on sublime and atom. I moved it to the riot-org, but never got around to doing it for the vs-code plugin.

**Comment by djbusby** [comment]
I'm also interested in having this functionality.  Of note is the PHP syntax mode is correctly able to comment both HTML, PHP, JavaScript and CSS -- all when they are in the same file.   I've noticed in the ./resources/app/extensions/php/package.json file (from an installed vscode) it shows a few different grammers -- maybe something similar can be added here?

**Comment by crisward** [comment]
Thanks @djbusby for your suggestion. As I'm not a big user of riot anymore (moved most of my code to svelte), I'm not planning on updating the plugin further. Feel free to fork / patch and submit a new plugin to microsoft vscode.

Or better still ask riot maintainers to to perhaps deploy their own vscode plugin. Their sublime one is here (based on my original I believe)

https://github.com/riot/syntax-highlight
