### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by phillip-haydon** [crisward/riot-tag#2]
Extension is working great, but would like to know if there is a way to default the language to Riot (HTML). At the moment anytime I open a file it defaults to Jade which I don't use.

**Comment by crisward** [comment]
If you're using vscode version one (just released) you can chose it when you set the language. Earlier versions of vscode didn't have this.

**Comment by phillip-haydon** [comment]
Hah I literally just worked it out. 

I guess for anyone else: in the user settings, add:

```
// Place your settings in this file to overwrite the default settings
{
     "files.associations": {
        "*.tag": "htmltag"
    }
}
```

Then restart VSCode

Thanks.

**Comment by melekhine** [comment]
https://github.com/crisward/riot-tag/issues/2#issuecomment-210778536

I think it should be in `readme.md`

**Comment by crisward** [comment]
Ok, I'll add it as soon as I get a chance. 
Thanks.

**Comment by crisward** [comment]
Added

https://github.com/crisward/riot-tag#installation
