### ISSUE TITLE
How about Emmet support for the html?

### ISSUE THREAD

**Issue by bryanj0410** [crisward/riot-tag#6]
I love the highlighting for riot tags, but it would be so wonderful if it supported emmet for creating the html.

**Comment by crisward** [comment]
Thanks for the suggestion... Not something I use myself. More than happy to accept a pull request if you have any idea how to get this to work with emmet.

**Comment by bryanj0410** [comment]
I will mess with it and see if I can come up with anything.

**Comment by drzippie** [comment]
adding:

```
"emmet.syntaxProfiles": {
        "htmltag": "html"
     }
```

Works as expected

![emmet](https://cloud.githubusercontent.com/assets/239421/19236201/892b23ce-8ef6-11e6-90e0-31e248dbcc1e.gif)

**Comment by crisward** [comment]
Just for clarification the notes are here - https://code.visualstudio.com/docs/languages/html#_emmet-snippets

As this is a per user preference I'll close this issue. It may be worth adding to the Readme in future.

**Comment by crisward** [comment]
btw thanks @drzippie
