### ISSUE TITLE
Comment Syntax is broken

### ISSUE THREAD

**Issue by daslicht** [crisward/riot-tag#7]
Hi, 
when I add a block comment (Riot html) I just get `s/` inserted or `<!--  -->`

Nice would be if it would be context sensitive

**Comment by crisward** [comment]
Guessing you worked it out

**Comment by daslicht** [comment]
yeah its adding anytime html comments. 

Is there a way to make JS comments work in js parts and html comments in html parts ?

**Comment by crisward** [comment]
I wish.... it's a pain I know.

VSCode last time I checked doesn't allow different comment styles for different code parts.

Discussed here https://github.com/crisward/riot-tag/issues/4

**Comment by daslicht** [comment]
yikes :) thank you for the reply
