### ISSUE TITLE
HTML / CSS support by default? 

### ISSUE THREAD

**Issue by jarben** [crisward/riot-tag#8]
Seems like I don't get any HTML and CSS support by default, only JS syntax highlight is supported: 
![image](https://cloud.githubusercontent.com/assets/561365/21349469/6a510c54-c6b2-11e6-809b-f56036ce8fb3.png)
...
![image](https://cloud.githubusercontent.com/assets/561365/21349478/72cc7a6c-c6b2-11e6-844d-9503fe1384e4.png)

Do I need to switch something on?

**Comment by crisward** [comment]
Weird, never had this issue. 

Below is what I get. The plugin relies on CSS and JS syntax highlighters within VSCode. I'm pretty sure these are built in plugins. It could be that you have another plugin installed which is hijacking their name spaces. To be honest I'm not sure.

<img width="292" alt="screen shot 2018-05-16 at 08 53 15" src="https://user-images.githubusercontent.com/3109157/40103815-a4a93210-58e6-11e8-8ba9-3af3746df2c1.png">

**Comment by crisward** [comment]
I'll close this for now. If you're still using this plugin, try disabling other plugins until the highlighting works. If you get anywhere with this, let me know. thanks.
